### ISSUE TITLE
Make error clearer when a binary fails to load (iltorb) because it was compiled for a different version/paltform

### ISSUE THREAD

**Issue by Leko** [sonarwhal/sonarwhal#1043]
The original report is kept at the end of this issue and it has evolved into the following:

sonarwhal uses `iltorb` which is a binary package. When updating versions of node without recompiling it, sonarwhal will fail loading saying that it can't find the resource `jsdom`. We should capture better this error for future users, node updates frequently so this will most likely happen again.

```
$ sonarwhal https://example.com
Error: Resource jsdom not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadResources (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:213:29)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:112:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
? There is 1 package from your .sonarwhalrc file not installed or with an incompatible version. Do you want us to try to install/update them? Yes
Installing packages...
✖ Error executing "npm install @sonarwhal/[object Object] -g"
Try executing:
    sudo npm install @sonarwhal/[object Object] -g
            manually to install all the packages.
```

-----------------------------------

Hi there.
I try to use sonarwhal but execution failed.

I think it is wired: `Can't require @sonarwhal/configuration-progressive-web-apps` (see output section)
@sonarwhal/configuration-progressive-web-apps exists into node_modules.

```
ls -la node_modules/@sonarwhal/configuration-progressive-web-apps/
total 56
drwxr-xr-x   7 leko  staff    238 May  6 17:49 .
drwxr-xr-x  11 leko  staff    374 May  6 17:49 ..
-rw-r--r--   1 leko  staff    305 Oct 26  1985 CHANGELOG.md
-rw-r--r--   1 leko  staff  11384 Oct 26  1985 LICENSE.txt
-rw-r--r--   1 leko  staff   1590 Oct 26  1985 README.md
-rw-r--r--   1 leko  staff    444 Oct 26  1985 index.json
-rw-r--r--   1 leko  staff   2236 May  6 17:49 package.json
```

## Environment

* __`sonarwhal` version:v1.8.1__
* __`Node.js` version:v8.9.0 and v10.0.0__
* __`npm` version:5.8.0 and 5.6.0__

I tested two version of Node.js (8.9.0 and 10.0.0)

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js
{
    "extends": [
        "progressive-web-apps"
    ]
}
```

</details>

## URL for which `sonarwhal` failed

* __URL:https://example.com__

## Output

<details>
<summary>sonarwhal’s raw output</summary>

```text
npx sonarwhal --debug https://example.com
  sonarwhal:utils:misc Loading JSON file: /usr/local/lib/node_modules/sonarwhal/package.json +0ms
  sonarwhal:utils:get-as-uri Adding valid target: https://example.com/ +0ms
  sonarwhal:cli:analyze Loading configuration file from /Users/leko/.ghq/github.com/Leko/ansitsu/.sonarwhalrc. +0ms
  sonarwhal:utils:misc Loading JSON file: /Users/leko/.ghq/github.com/Leko/ansitsu/.sonarwhalrc +97ms
  sonarwhal:config:config-validator Validating configuration +0ms
  sonarwhal:config Composing configuration from extends +0ms
  sonarwhal:utils:resource-loader Searching progressive-web-apps… +0ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/configuration-progressive-web-apps +1ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-configuration-progressive-web-apps +0ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/configurations/progressive-web-apps/progressive-web-apps.js +1ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/.ghq/github.com/Leko/ansitsu +2ms
  sonarwhal:utils:resource-loader Resource progressive-web-apps not found +0ms
Error: Resource progressive-web-apps not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadConfiguration (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:208:20)
    at userConfig.extends.map (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:38:52)
    at Array.map (<anonymous>)
    at composeConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:37:47)
    at Function.fromConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:161:28)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:111:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:267:14)
    at <anonymous>
Exit code: 1
```

</details>

**Comment by molant** [comment]
From you output it looks like you are using npx. We currently have a big with that: https://github.com/sonarwhal/sonarwhal/issues/1021 😔

The work around is to install it for now (globally or as a dependency). Can you give it a try an let us know if that fixes it?

**Comment by Leko** [comment]
@molant

## Globally
it's not working (same problem).

<details>
<summary>sonarwhal’s raw output</summary>



```
$ npm install -g --engine-strict sonarwhal
/usr/local/bin/sonarwhal -> /usr/local/lib/node_modules/sonarwhal/dist/src/bin/sonarwhal.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @sonarwhal/connector-edge@1.0.0 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @sonarwhal/connector-edge@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: edge-diagnostics-adapter@0.6.0 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge/node_modules/edge-diagnostics-adapter):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for edge-diagnostics-adapter@0.6.0: wanted {"os":"win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: regedit@2.2.7 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge/node_modules/regedit):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for regedit@2.2.7: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-windows@0.1.14 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge/node_modules/node-windows):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for node-windows@0.1.14: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

$ sonarwhal -v
v1.8.1

$ sonarwhal https://example.com
Error: Resource progressive-web-apps not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadConfiguration (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:208:20)
    at userConfig.extends.map (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:38:52)
    at Array.map (<anonymous>)
    at composeConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:37:47)
    at Function.fromConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:161:28)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:111:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

</details>

## Locally
It seems works!
But it has error during build script. It's ok?

<details>
<summary>sonarwhal’s raw output</summary>



```
$ npm install -D --engine-strict sonarwhal

> fsevents@1.2.3 install /Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/fsevents
> node install

[fsevents] Success: "/Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> canvas-prebuilt@1.6.5-prerelease.1 install /Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/canvas-prebuilt
> node-pre-gyp install

[canvas-prebuilt] Success: "/Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node" is installed via remote

> iltorb@2.3.1 install /Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

/Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/prebuild-install/util.js:71
  return path.join(prebuildCache(), url.replace(/[^a-zA-Z0-9.]+/g, '-'))
                                        ^

TypeError: url.replace is not a function
    at Object.cachedPrebuild (/Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/prebuild-install/util.js:71:41)
    at downloadPrebuild (/Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/prebuild-install/download.js:17:29)
    at Object.<anonymous> (/Users/leko/.ghq/github.com/Leko/ansitsu/node_modules/sonarwhal/node_modules/iltorb/scripts/install.js:47:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
  CC(target) Release/obj.target/iltorb/brotli/c/common/dictionary.o
  CC(target) Release/obj.target/iltorb/brotli/c/common/transform.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/bit_reader.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/decode.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/huffman.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/state.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references_hq.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/bit_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/block_splitter.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/brotli_bit_stream.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/cluster.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment_two_pass.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/dictionary_hash.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encoder_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/entropy_encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/histogram.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/literal_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/memory.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/metablock.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/static_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/utf8_util.o
  CXX(target) Release/obj.target/iltorb/src/common/allocator.o
  CXX(target) Release/obj.target/iltorb/src/common/stream_coder.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode_worker.o
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode.o
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode_worker.o
  CXX(target) Release/obj.target/iltorb/src/iltorb.o
  SOLINK_MODULE(target) Release/iltorb.node
  COPY ../build/bindings/iltorb.node
  TOUCH Release/obj.target/action_after_build.stamp
+ sonarwhal@1.8.1
added 646 packages in 83.605s

$ $(npm bin)/sonarwhal -v
v1.8.1

$ $(npm bin)/sonarwhal https://example.com
✖ Finishing...
apple-touch-icons  1 error
manifest-exists    1 error
✖ Found a total of 2 errors and 0 warnings
```

</details>

**Comment by molant** [comment]
I believe the local output is expected. It's part of the `iltorb` dependency and when it fails it fallsback to build so it's fine.

OK, I think I have an idea of what's going on. When running sonarwhal globally, you have to execute from a folder that does not have any `package.json`. If there's a `package.json` then you should install everything as a dev dependency.


What I just did on my machine:

```bash
npm install -g sonarwhal
npm install -g @sonarwhal/configuration-progressive-web-apps`
```

Create a new empty folder and a `.sonarwhalrc` in it (or put it in your `home` folder):

```json
{
    "extends": [
        "progressive-web-apps"
    ]
}
```
And then from that folder (or anyone without a `package.json`) run `sonarwhal https://example.com`

Let me know if this fixes and if so I'll open an issue to see what we can do to improve the experience.

**Comment by Leko** [comment]
@molant 

> I believe the local output is expected. It's part of the iltorb dependency and when it fails it fallsback to build so it's fine.

I see.

---

I tried to execute without package.json. It's not working.

```
$ ls -la
total 8
drwxr-xr-x    3 leko  staff   102 May  7 20:45 .
drwx------+ 252 leko  staff  8568 May  7 20:42 ..
-rw-r--r--    1 leko  staff    57 May  7 20:45 .sonarwhalrc

$ npm install -g sonarwhal
/usr/local/bin/sonarwhal -> /usr/local/lib/node_modules/sonarwhal/dist/src/bin/sonarwhal.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @sonarwhal/connector-edge@1.0.0 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @sonarwhal/connector-edge@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: edge-diagnostics-adapter@0.6.0 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge/node_modules/edge-diagnostics-adapter):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for edge-diagnostics-adapter@0.6.0: wanted {"os":"win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: regedit@2.2.7 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge/node_modules/regedit):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for regedit@2.2.7: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-windows@0.1.14 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge/node_modules/node-windows):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for node-windows@0.1.14: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

+ sonarwhal@1.8.1
added 189 packages and updated 1 package in 9.576s

$ npm install -g @sonarwhal/configuration-progressive-web-apps
npm WARN @sonarwhal/configuration-progressive-web-apps@2.0.0 requires a peer of sonarwhal@^1.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/formatter-summary@2.0.2 requires a peer of sonarwhal@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-exists@4.0.1 requires a peer of sonarwhal@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-file-extension@4.0.1 requires a peer of sonarwhal@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/parser-manifest@1.0.2 requires a peer of sonarwhal@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-app-name@4.0.2 requires a peer of sonarwhal@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-is-valid@5.0.1 requires a peer of sonarwhal@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-apple-touch-icons@3.0.2 requires a peer of sonarwhal@^1.7.0 but none is installed. You must install peer dependencies yourself.

+ @sonarwhal/configuration-progressive-web-apps@2.0.0
added 28 packages in 4.033s

$ sonarwhal https://example.com
Error: Resource jsdom not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadResources (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:213:29)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:112:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
? There is 1 package from your .sonarwhalrc file not installed or with an incompatible version. Do you want us to try to install/update them? Yes
Installing packages...
✖ Error executing "npm install @sonarwhal/[object Object] -g"
Try executing:
    sudo npm install @sonarwhal/[object Object] -g
            manually to install all the packages.
```

**Comment by molant** [comment]
@Leko and `.sonarwhalrc` is still?

```json
{
    "extends": [
        "progressive-web-apps"
    ]
}
```

> There is 1 package from your .sonarwhalrc file not installed or with an incompatible version. Do you want us to try to install/update them?

I'm clueless about why sonarwhal can't find `jsdom` and later tell you `Error executing "npm install @sonarwhal/[object Object] -g"`

Do you mind trying with this config:

```json
{
    "connector": "jsdom"
    "extends": [
        "progressive-web-apps"
    ]
}
```

**Comment by Leko** [comment]
@molant Yes.

```
$ cat .sonarwhalrc
{
    "extends": [
        "progressive-web-apps"
    ]
}
```

And I tried to update .sonarwhalrc but not working still.

```
$ cat .sonarwhalrc
{
    "connector": "jsdom",
    "extends": [
        "progressive-web-apps"
    ]
}

$ sonarwhal https://example.com
Error: Resource jsdom not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadResources (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:213:29)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:112:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
? There is 1 package from your .sonarwhalrc file not installed or with an incompatible version. Do you want us to try to install/update them? Yes
Installing packages...
✖ Error executing "npm install @sonarwhal/[object Object] -g"
Try executing:
    sudo npm install @sonarwhal/[object Object] -g
            manually to install all the packages.
```

---

I found a bug.
In dist/src/lib/cli/analyze.js,

```js
        const missingPackages = resources.missing.map((name) => {
            return `@sonarwhal/${name}`;
        });
        const incompatiblePackages = resources.incompatible.map((name) => {
            return `@sonarwhal/${name}`;
        });
```

`resources.missing` is `[ { name: 'jsdom', options: {} } ]`. Not `'jsdom'`.

**Comment by molant** [comment]
@sarvaje can you take a look at this? I'll be at //Build/ tomorrow and I don't think I'll have time to investigate this properly. We should at least fix what @Leko has just reported.

@Leko, can you run sonarwhal again with the --debug option? The output should be different than your firat one because it's jsdom the one missing now (which is bundled in sonarwhal so I don't know why it can't find it).

Also, if you replace jsdom with chrome does it work (you'll need to have chrome installed)?

Thanks!

**Comment by Leko** [comment]
@molant I got it. output is here:

```
sonarwhal --debug  https://example.com
  sonarwhal:utils:misc Loading JSON file: /usr/local/lib/node_modules/sonarwhal/package.json +0ms
  sonarwhal:utils:get-as-uri Adding valid target: https://example.com/ +0ms
  sonarwhal:cli:analyze Loading configuration file from /Users/leko/Downloads/aaa/.sonarwhalrc. +0ms
  sonarwhal:utils:misc Loading JSON file: /Users/leko/Downloads/aaa/.sonarwhalrc +53ms
  sonarwhal:config:config-validator Validating configuration +0ms
  sonarwhal:config Composing configuration from extends +0ms
  sonarwhal:utils:resource-loader Searching progressive-web-apps… +0ms
  sonarwhal:utils:resource-loader progressive-web-apps found in @sonarwhal/configuration-progressive-web-apps +1ms
  sonarwhal:config:config-validator Validating configuration +15ms
  sonarwhal:config Composing configuration from extends +1ms
  sonarwhal:config overriding config settings with values provided via CLI +1ms
  sonarwhal:config Initializing ignored urls +3ms
  sonarwhal:utils:resource-loader Searching jsdom… +4ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +40ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/connector-jsdom +0ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-connector-jsdom +0ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/connectors/jsdom/jsdom.js +361ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader Resource jsdom not found +0ms
Error: Resource jsdom not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadResources (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:213:29)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:112:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  sonarwhal:utils:resource-loader Searching apple-touch-icons… +2ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +8ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/rule-apple-touch-icons +0ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-rule-apple-touch-icons +1ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/rules/apple-touch-icons/apple-touch-icons.js +0ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader apple-touch-icons found in /usr/local/lib/node_modules/@sonarwhal/configuration-progressive-web-apps/node_modules/@sonarwhal/rule-apple-touch-icons +4ms
  sonarwhal:utils:resource-loader Searching manifest-app-name… +3ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +8ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/rule-manifest-app-name +1ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-rule-manifest-app-name +0ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/rules/manifest-app-name/manifest-app-name.js +0ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader manifest-app-name found in /usr/local/lib/node_modules/@sonarwhal/configuration-progressive-web-apps/node_modules/@sonarwhal/rule-manifest-app-name +2ms
  sonarwhal:utils:resource-loader Searching manifest-exists… +0ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +9ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/rule-manifest-exists +0ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-rule-manifest-exists +0ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/rules/manifest-exists/manifest-exists.js +0ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader manifest-exists found in /usr/local/lib/node_modules/@sonarwhal/configuration-progressive-web-apps/node_modules/@sonarwhal/rule-manifest-exists +1ms
  sonarwhal:utils:resource-loader Searching manifest-file-extension… +18ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +6ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/rule-manifest-file-extension +1ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-rule-manifest-file-extension +0ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/rules/manifest-file-extension/manifest-file-extension.js +0ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader manifest-file-extension found in /usr/local/lib/node_modules/@sonarwhal/configuration-progressive-web-apps/node_modules/@sonarwhal/rule-manifest-file-extension +1ms
  sonarwhal:utils:resource-loader Searching manifest-is-valid… +0ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +7ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/rule-manifest-is-valid +0ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-rule-manifest-is-valid +1ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/rules/manifest-is-valid/manifest-is-valid.js +0ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader manifest-is-valid found in /usr/local/lib/node_modules/@sonarwhal/configuration-progressive-web-apps/node_modules/@sonarwhal/rule-manifest-is-valid +6ms
  sonarwhal:utils:resource-loader Searching manifest… +1ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +11ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/parser-manifest +0ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-parser-manifest +0ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/parsers/manifest/manifest.js +0ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader manifest found in /usr/local/lib/node_modules/@sonarwhal/configuration-progressive-web-apps/node_modules/@sonarwhal/parser-manifest +1ms
  sonarwhal:utils:resource-loader Searching summary… +0ms
  sonarwhal:utils:resource-loader Package sonarwhal-configuration-progressive-web-apps not found +7ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/formatter-summary +0ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-formatter-summary +1ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/formatters/summary/summary.js +0ms
  sonarwhal:utils:resource-loader Can't require /Users/leko/Downloads/aaa +0ms
  sonarwhal:utils:resource-loader summary found in /usr/local/lib/node_modules/@sonarwhal/configuration-progressive-web-apps/node_modules/@sonarwhal/formatter-summary +21ms
? There is 1 package from your .sonarwhalrc file not installed or with an incompatible version. Do you want us to try to install/update them? Yes
  sonarwhal:utils:npm Running command npm install @sonarwhal/[object Object] -g +0ms
Installing packages...
- Running command: npm install @sonarwhal/[object Object] -g  sonarwhal:utils:npm npm ERR! code EINVALIDTAGNAME
  sonarwhal:utils:npm npm ERR! Invalid tag name "Object]": Tags may not have any characters that encodeURIComponent encodes.
  sonarwhal:utils:npm
  sonarwhal:utils:npm npm ERR! A complete log of this run can be found in:
  sonarwhal:utils:npm npm ERR!     /Users/leko/.npm/_logs/2018-05-08T13_29_29_637Z-debug.log
  sonarwhal:utils:npm  +3s
✖ Error executing "npm install @sonarwhal/[object Object] -g"
Try executing:
    sudo npm install @sonarwhal/[object Object] -g
            manually to install all the packages.
Exit code: 1
```

I debugged about this line.

`  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/connectors/jsdom/jsdom.js +361ms`

An error is here. 

```
Error: The module '/usr/local/lib/node_modules/sonarwhal/node_modules/iltorb/build/bindings/iltorb.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
...
```

It's my mistake.
I removed sonarwhal globally and re-run `npm install -g --engine-strict sonarwhal`.
It works fine.

```
sonarwhal:utils:resource-loader jsdom found in /usr/local/lib/node_modules/sonarwhal/dist/src/lib/connectors/jsdom/jsdom.js +442ms
...
apple-touch-icons  1 error
manifest-exists    1 error
✖ Found a total of 2 errors and 0 warnings
  sonarwhal:cli:analyze Total runtime: 2564ms +3s
Exit code: 1
```

I installed it into another Node.js version (In v10.0) but I run it in v8.9.
Thanks.

**Comment by sarvaje** [comment]
Hi! There is something else I can do, or it is working now?

**Comment by molant** [comment]
@sarvaje I think we could capture when we fail loading `iltorb` (or something that depends on it) because it was compiled for a different version of node. Not sure where we would put this though.

I'll update the title and description of the issue.

@Leko thanks a lot for helping us identify this!
