### ISSUE TITLE
Fix: `BrowserslistError: Unknown version` issue 

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#1109]
```
 BrowserslistError: Unknown version 66 of android
    at Function.select (/Users/xxxxx/projects/tmp/node_modules/@sonarwhal/rule-disown-opener/node_modules/browserslist/index.js:622:17)
    at /Users/xxxxx/projects/tmp/node_modules/@sonarwhal/rule-disown-opener/node_modules/browserslist/index.js:151:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/xxxxx/projects/tmp/node_modules/@sonarwhal/rule-disown-opener/node_modules/browserslist/index.js:132:18)
    at browserslist (/Users/xxxxx/projects/tmp/node_modules/@sonarwhal/rule-disown-opener/node_modules/browserslist/index.js:224:16)
    at Object.isSupported (/Users/xxxxx/projects/tmp/node_modules/@sonarwhal/rule-disown-opener/node_modules/caniuse-api/dist/index.js:62:37)
    at validate (/Users/xxxxx/projects/tmp/node_modules/@sonarwhal/rule-disown-opener/dist/src/rule.js:75:53)
    at Immediate.setImmediate (/Users/xxxxx/projects/tmp/node_modules/sonarwhal/dist/src/lib/sonarwhal.js:113:46)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by sarvaje** [comment]
I'm going to try to explain the current situation.

The rule `disown-opener` fails because of that error when it try to check if the property `rel-noopener` is supported `isSupported`.

But, if I create a new project with this code:
```
const caniuse = require('caniuse-api');

const browsers = "and_chr 66,and_ff 60,and_qq 1.2,and_uc 11.8,android 66,android 4.4.3-4.4.4,android 4.4,baidu 7.12,chrome 66,chrome 65,chrome 64,chrome 49,edge 17,edge 16,firefox 60,firefox 59,firefox 52,ie 11,ie_mob 11,ios_saf 11.3,ios_saf 11.0-11.2,ios_saf 10.3,op_mini all,op_mob 46,opera 53,opera 52,safari 11.1,safari 11,samsung 6.2,samsung 5,samsung 4";

const supported = caniuse.isSupported('rel-noopener', browsers)

console.log(supported);
`
Then it is working.

`caniuse-api` install browserslist 2.11.3 in both cases, `sonarwhal` and the new project, but in sonarwhal fails

Also, I tried to install just browserslist 2.11.3 in a new project and `browserslist('android 66')` works, so it looks like for some reason, in sonarwhal something is different :s

Any idea about what is happening?

**Comment by sarvaje** [comment]
We found out the problem. The problem is that `sonarwhal` and `@sonarwhal/rule-disown-opnener` install different version of `caniuse-lite` (this is a dependency of `browserlist`). And that is because, at the moment we publish the rule, the version of `caniuse-lite` was older than when we publish the latest version of `sonarwhal`.

To avoid this problem, what I'm going to do is move the logic depending of `caniuse-api` (this is the packages that install `browserlist` and `caniuse-lite` in the rule) to sonarwhal as a `util`.
