### ISSUE TITLE
"TypeError: Cannot read property 'response' of undefined" while testing

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#1158]
I'm getting the following message a few times while runnint the tests of the rules/hints:

```bash
TypeError: Cannot read property 'response' of undefined
    at ChromeConnector.get headers [as headers] (C:\projects\@sonarwhal\sonarwhal\packages\utils-debugging-protocol-common\src\debugging-protocol-connector.ts:1034:40)
    at Chrome.<anonymous> (C:\projects\@sonarwhal\sonarwhal\packages\utils-debugging-protocol-common\src\debugging-protocol-connector.ts:750:59)
    at <anonymous>
```

This happens with the CDP and on Windows 10 17704. It's probably a race condition when we are running multiple tests (maybe chrome not keeping up on my machine?). Will be good to investigate a bit.

**Comment by molant** [comment]
From what I've seen sometimes the `onLoadEventFired` is called before we've received/process the `onResponseReceived` for the target so we try to access the `headers` and fail because `response` doesn't exist.

We should:
- Add a check to make sure the response has been received or queue it up
- Add a check to not crash when accessing any properties that might not be set up yet

**Comment by molant** [comment]
This might solve #1143
