### ISSUE TITLE
Timeout with some urls

### ISSUE THREAD

**Issue by SeriyVol4ishe** [sonarwhal/sonarwhal#811]
Sonarwhal version:
`v0.25.0`
Url that I tried:
`http://forumodua.com/`
Output:
```
Unhandled rejection promise:
    uri: undefined
    message: ESOCKETTIMEDOUT
    stack:
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/sonarwhal/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```
I use jsdom as connector.

**Comment by sarvaje** [comment]
I'm not sure, I need to take a look.

**Comment by molant** [comment]
> This should be fix by https://github.com/sonarwhal/sonarwhal/commit/a5602ecc9a88034400862bb8a9e2e0390275519e, right?

I don't think so. That fix is to wait for the browser to be closed completely so we don't have issues when running the tests. In a regular scenario of 1 url it shouldn't have any impact.

**Comment by qzhou1607** [comment]
I can reproduce this error in the beginning, but the error disappeared after I pulled in the latest code 😔 . Now I can't reproduce this error in v1.0.4 using jsdom. Can somebody else also try it and confirm that it is still an issue?

**Comment by molant** [comment]
I've installed 1.0.5 and I didn't get any issue with that site.
@SeriyVol4ishe if you still have issues with the latest version please open a new issue.

Thanks!
