### ISSUE TITLE
Not able to install sonarwhal version 0.26.0

### ISSUE THREAD

**Issue by hgakhr** [sonarwhal/sonarwhal#831]
Hi Team,

I am getting an issue in installing the latest version of the sonarhwal.

/ # sonarwhal -v
v0.26.0
/ # npm -v
5.5.1
/ # node -v
v8.9.3

This was working perfectly fine with 0.25.0 version . But now it is not working .

Error 

```
/ # sonarwhal --init
Welcome to sonarwhal configuration generator
? What connector do you want to use? jsdom
? What formatter do you want to use? stylish
? Do you want to use the recommended rules configuration? Yes
Using recommended rules
? What browsers are you targeting? Default (last 2 versions of each browser, and browsers with globaly usage over 1%, plus Firefox ESR)
Error: npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-21T17_16_32_031Z-debug.log

    at installRules (/node_modules/sonarwhal/dist/src/lib/cli/init.js:31:19)
    at exports.initSonarwhalrc (/node_modules/sonarwhal/dist/src/lib/cli/init.js:130:11)
    at <anonymous>
Something went wrong installing the packages, please run:
sudo npm install  -g
to install all the rules.


/ # sonarwhal http://www.google.com
Error: Resource apple-touch-icons not found
    at Object.exports.loadResource (/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:117:15)
    at rulesIds.reduce (/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:140:30)
    at Array.reduce (<anonymous>)
    at Object.exports.loadRules (/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:139:28)
    at Sonarwhal.initRules (/node_modules/sonarwhal/dist/src/lib/sonarwhal.js:127:38)
    at new Sonarwhal (/node_modules/sonarwhal/dist/src/lib/sonarwhal.js:79:14)
    at exports.analyze (/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:93:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Can you please help in resolving this issue.
or is their any way i can rollback to older version (0.25.0) for now and continue my testing?

Thanks,
Hitesh

**Comment by sarvaje** [comment]
@hgakhr Until we fix that, you need to choose `No` for the option `Do you want to use the recommended rules configuration`.

**Comment by molant** [comment]
You can install it via `npm install -g sonarwhal@0.25.0`

**Comment by alrra** [comment]
Closing as doing `npm install -g sonarwhal should now point to `v0.25.0`, which works.
