### ISSUE TITLE
Fix `rule-typescript-config`

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#872]
Running the tests, I get:

```bash
/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172
        throw new Error(`Resource ${name} not found`);
        ^

Error: Resource typescript-config/is-valid not found
    at Object.exports.loadResource (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadRule (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:205:20)
    at Object.exports.testLocalRule (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/sonarwhal/dist/tests/helpers/rule-runner.js:134:33)
    at Object.<anonymous> (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/tests/is-valid.ts:43:12)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at extensions.(anonymous function) (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/require-precompiled/index.js:13:11)
    at /Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/ava/lib/test-worker.js:62:1)
    at Module._compile (module.js:635:30)
    at Module.replacementCompile (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/xxxxx/projects/sonarwhal/packages/rule-typescript-config/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

**Comment by sarvaje** [comment]
@alrra I can't reproduce this error.
I have run the tests form the root and from `packages/rule-typescript-config`.

**Comment by alrra** [comment]
@sarvaje Weird, things also works for me now.

However the`.nycrc` path](https://github.com/sonarwhal/sonarwhal/blob/6765280f4e16aad2b0727471cfec1ac0c6817a3e/packages/rule-typescript-config/package.json#L51) is wrong (I will fix that).
