### ISSUE TITLE
Unable to create  a valid configuration file

### ISSUE THREAD

**Issue by awentzel** [sonarwhal/sonarwhal#984]
First attempt at setting up Sonarwhal using the generator resulting in an error.

## Environment
```
$ sonarwhal -v
v1.4.0
$ node -v
v8.11.1
$ npm -v
5.6.0

```
## `sonarwhal` configuration
```
{
    "extends": [
        "web-recommended"
    ]
}
```
<details>
<summary>sonarwhal’s configuration</summary>

```js



```

</details>

## URL for which `sonarwhal` failed

* __URL:__ https://fluentweb.com or https://localhost:7001

## Output
```
Welcome to sonarwhal configuration generator
? Do you want to use a predefined configuration or create your own based on your installed packages? predefined
? Choose the configuration you want to extend from web-recommended
Installing packages...
✔ Running command: npm install @sonarwhal/configuration-web-recommended
Configuration file .sonarwhalrc was created.
Error: Resource web-recommended not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadConfiguration (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:208:20)
    at userConfig.extends.map (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:38:52)
    at Array.map (<anonymous>)
    at composeConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:37:47)
    at Function.fromConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:142:28)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:111:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
MBP:fast-components-react-msft awentzel$
```
<details>
<summary>sonarwhal’s raw output</summary>

```
$ sonarwhal --debug https://fluentweb.com
  sonarwhal:utils:misc Loading JSON file: /usr/local/lib/node_modules/sonarwhal/package.json +0ms
  sonarwhal:utils:get-as-uri Adding valid target: https://fluentweb.com/ +0ms
  sonarwhal:cli:analyze Loading configuration file from /Users/aaronw/aWork/Microsoft/Projects/FluentWeb/fast-dna/packages/fast-components-react-msft/.sonarwhalrc. +0ms
  sonarwhal:utils:misc Loading JSON file: /Users/aaronw/aWork/Microsoft/Projects/FluentWeb/fast-dna/packages/fast-components-react-msft/.sonarwhalrc +101ms
  sonarwhal:config:config-validator Validating configuration +0ms
  sonarwhal:config Composing configuration from extends +0ms
  sonarwhal:utils:resource-loader Searching web-recommended… +0ms
  sonarwhal:utils:resource-loader Can't require @sonarwhal/configuration-web-recommended +1ms
  sonarwhal:utils:resource-loader Can't require sonarwhal-configuration-web-recommended +0ms
  sonarwhal:utils:resource-loader Can't require /usr/local/lib/node_modules/sonarwhal/dist/src/lib/configurations/web-recommended/web-recommended.js +1ms
  sonarwhal:utils:resource-loader Can't require /Users/aaronw/aWork/Microsoft/Projects/FluentWeb/fast-dna/packages/fast-components-react-msft +1ms
  sonarwhal:utils:resource-loader Resource web-recommended not found +0ms
Error: Resource web-recommended not found
    at Object.exports.loadResource (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:172:15)
    at Object.exports.loadConfiguration (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/utils/resource-loader.js:208:20)
    at userConfig.extends.map (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:38:52)
    at Array.map (<anonymous>)
    at composeConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:37:47)
    at Function.fromConfig (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/config.js:142:28)
    at exports.analyze (/usr/local/lib/node_modules/sonarwhal/dist/src/lib/cli/analyze.js:111:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Exit code: 1
$
```
```text



```

</details>

**Comment by alrra** [comment]
@awentzel It seems you have `sonarwhal` installed globally but the wizard didn't install it using `-g`:

> ✔ Running command: npm install @sonarwhal/configuration-web-recommended

Can you run `npm i -g @sonarwhal/configuration-web-recommended` 

And then, run `sonarwhal` again? Thanks.

**Comment by alrra** [comment]
@sonarwhal/core I wasn't able to reproduce this. :(

---

@awentzel Also, can you offer more information about your environment. What OS are you using? Are you use something like `nvm`? etc. Thanks!

**Comment by molant** [comment]
@awentzel I believe this is what happened to you:

1. You installed `sonarwhal` globally
1. Then move to a folder with a `package.json` and try to run it via the CLI
1. You were prompted to install the configuration and because there's a `package.json` already there then `sonarwhal` thought you had it installed locally and then you got that error

Can you please confirm this? If so I'll update the title of the bug and track it as a bug.

If you are going to use it on a project, we recommend to install it as a dev dependency, same you would do with ESLint or any similar tool, and run it via npm scripts.

Thanks!

**Comment by awentzel** [comment]
@alrra, I'm running MacOS 10.13.4 (17E199), Node.  I tried again, following your instructions and ran `npm i -g @sonarwhal/configuration-web-recommended` after `npm -g install --save-dev sonarwhal ` and it other than a bunch of warnings it did succeed.

@molant, you are correct.  Initially, I followed the instructions from https://sonarwhal.com/docs/user-guide/ which did not work for me.  

## Warnings for reference
```
npm WARN @sonarwhal/configuration-web-recommended@4.0.0 requires a peer of sonarwhal@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/formatter-stylish@2.0.1 requires a peer of sonarwhal@^1.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-highest-available-document-mode@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/formatter-codeframe@2.0.1 requires a peer of sonarwhal@^1.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-http-cache@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-html-checker@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-image-optimization-cloudinary@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-disown-opener@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-content-type@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-apple-touch-icons@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/formatter-summary@2.0.1 requires a peer of sonarwhal@^1.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-axe@4.0.0 requires a peer of sonarwhal@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-http-compression@4.0.0 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-app-name@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-exists@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-no-html-only-headers@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-file-extension@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-manifest-is-valid@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-meta-viewport@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-no-bom@2.0.0 requires a peer of sonarwhal@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-no-disallowed-headers@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-meta-charset-utf-8@3.0.1 requires a peer of sonarwhal@^1.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-no-friendly-error-pages@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-no-protocol-relative-urls@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-no-http-redirects@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-ssllabs@3.0.2 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-no-vulnerable-javascript-libraries@3.1.0 requires a peer of sonarwhal@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-sri@1.0.2 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-validate-set-cookie-header@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-strict-transport-security@3.0.1 requires a peer of sonarwhal@^1.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN @sonarwhal/rule-x-content-type-options@3.0.0 requires a peer of sonarwhal@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @sonarwhal/connector-edge@1.0.0 (node_modules/@sonarwhal/configuration-web-recommended/node_modules/@sonarwhal/rule-sri/node_modules/@sonarwhal/connector-edge):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @sonarwhal/connector-edge@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @sonarwhal/connector-edge@1.0.0 (node_modules/@sonarwhal/configuration-web-recommended/node_modules/@sonarwhal/rule-no-bom/node_modules/@sonarwhal/connector-edge):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @sonarwhal/connector-edge@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: edge-diagnostics-adapter@0.6.0 (node_modules/@sonarwhal/configuration-web-recommended/node_modules/@sonarwhal/rule-no-bom/node_modules/@sonarwhal/connector-edge/node_modules/edge-diagnostics-adapter):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for edge-diagnostics-adapter@0.6.0: wanted {"os":"win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"x64"})
```

**Comment by alrra** [comment]
> and it other than a bunch of warnings it did succeed.

@awentzel awentzel Can you also tell me what `npm ls -g --depth=0` gives you? Thanks!
